CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    DisplayName NVARCHAR(120) NOT NULL,
    Email NVARCHAR(256) NOT NULL UNIQUE,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Networks (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    OwnerUserId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(160) NOT NULL,
    Description NVARCHAR(800) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Networks_Users FOREIGN KEY (OwnerUserId) REFERENCES Users(Id)
);

CREATE TABLE Devices (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    NetworkId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(120) NOT NULL,
    DeviceType NVARCHAR(40) NOT NULL,
    IpAddress NVARCHAR(45) NULL,
    MacAddress NVARCHAR(32) NULL,
    PositionX FLOAT NOT NULL DEFAULT 0,
    PositionY FLOAT NOT NULL DEFAULT 0,
    PositionZ FLOAT NOT NULL DEFAULT 0,
    Status NVARCHAR(24) NOT NULL DEFAULT 'Online',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Devices_Networks FOREIGN KEY (NetworkId) REFERENCES Networks(Id),
    CONSTRAINT CK_Devices_DeviceType CHECK (DeviceType IN ('Pc', 'Server', 'Switch', 'Router', 'Printer')),
    CONSTRAINT CK_Devices_Status CHECK (Status IN ('Online', 'Warning', 'Offline'))
);

CREATE TABLE Links (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    NetworkId UNIQUEIDENTIFIER NOT NULL,
    SourceDeviceId UNIQUEIDENTIFIER NOT NULL,
    TargetDeviceId UNIQUEIDENTIFIER NOT NULL,
    BandwidthMbps INT NOT NULL DEFAULT 1000,
    LatencyMs FLOAT NOT NULL DEFAULT 1,
    PacketLossPercent FLOAT NOT NULL DEFAULT 0,
    CONSTRAINT FK_Links_Networks FOREIGN KEY (NetworkId) REFERENCES Networks(Id),
    CONSTRAINT FK_Links_SourceDevices FOREIGN KEY (SourceDeviceId) REFERENCES Devices(Id),
    CONSTRAINT FK_Links_TargetDevices FOREIGN KEY (TargetDeviceId) REFERENCES Devices(Id)
);

CREATE TABLE DeviceMetrics (
    Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DeviceId UNIQUEIDENTIFIER NOT NULL,
    CpuPercent FLOAT NOT NULL,
    MemoryPercent FLOAT NOT NULL,
    TrafficInMbps FLOAT NOT NULL,
    TrafficOutMbps FLOAT NOT NULL,
    RecordedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_DeviceMetrics_Devices FOREIGN KEY (DeviceId) REFERENCES Devices(Id)
);

CREATE INDEX IX_Devices_NetworkId ON Devices(NetworkId);
CREATE INDEX IX_Links_NetworkId ON Links(NetworkId);
CREATE INDEX IX_DeviceMetrics_DeviceId_RecordedAt ON DeviceMetrics(DeviceId, RecordedAt DESC);

